# Generated by Django 5.2.7 on 2025-11-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercvdata',
            name='interview_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Interview Status'),
        ),
    ]
