# Generated by Django 5.2.7 on 2026-05-20 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0011_remove_employee_department_employee_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255, verbose_name='Asset Name')),
                ('asset_tag', models.CharField(max_length=128, unique=True, verbose_name='Asset Tag / ID')),
                ('category', models.CharField(max_length=128, verbose_name='Category')),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial Number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('needs_repair', 'Needs Repair')], default='good', max_length=32)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('returned', 'Returned'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=32)),
                ('assigned_date', models.DateField(blank=True, null=True, verbose_name='Assigned Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='employee_management.employee', verbose_name='Employee Name')),
            ],
            options={
                'db_table': 'asset_management_asset',
                'ordering': ['-assigned_date', '-created_at', '-id'],
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
