# Generated by Django 5.0.2 on 2025-11-13 07:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, help_text='Unique employee identification code', max_length=64, null=True, unique=True)),
                ('employment_status', models.CharField(blank=True, help_text='E.g., Permanent, Contract, Probation', max_length=64, null=True)),
                ('employment_type', models.CharField(blank=True, help_text='E.g., Full-time, Part-time, Intern', max_length=64, null=True)),
                ('department', models.CharField(blank=True, help_text='Department name', max_length=128, null=True)),
                ('designation', models.CharField(blank=True, help_text='Job designation/title', max_length=128, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('allowances', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='PF Number')),
                ('esi_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='ESI Number')),
                ('pan_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='PAN Number')),
                ('account_holder_name', models.CharField(blank=True, max_length=128, null=True)),
                ('salary_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('salary_bank_name', models.CharField(blank=True, max_length=128, null=True)),
                ('salary_ifsc_code', models.CharField(blank=True, max_length=32, null=True)),
                ('salary_branch', models.CharField(blank=True, max_length=128, null=True)),
                ('pan_card_attachment', models.FileField(blank=True, null=True, upload_to='employees/pan/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='employees/offer_letters/')),
                ('joining_letter', models.FileField(blank=True, null=True, upload_to='employees/joining_letters/')),
                ('id_card_attachment', models.FileField(blank=True, null=True, upload_to='employees/id_cards/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=128, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=64, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=8, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('reporting_manager', models.ForeignKey(blank=True, help_text='Direct reporting manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employee_management.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee_management_employee',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, help_text='Type of document (e.g., Certificate, License)', max_length=64, null=True)),
                ('title', models.CharField(blank=True, help_text='Document title', max_length=255, null=True)),
                ('document_file', models.FileField(upload_to='employees/documents/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='employee_management.employee')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'db_table': 'employee_management_employeedocument',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
