# Generated by Django 5.0.2 on 2025-11-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID (defaults to User ID, can be customized)', max_length=64, null=True, unique=True, verbose_name='Employee ID'),
        ),
    ]
