# Generated by Django 5.0.2 on 2025-11-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_remove_employee_employee_code_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhar number', max_length=12, null=True, verbose_name='Aadhar Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='duty_time',
            field=models.CharField(blank=True, help_text='E.g., 9:00 AM - 6:00 PM', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, help_text='Employee location/place (e.g., City, State, Country)', max_length=255, null=True, verbose_name='Employee Location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, help_text='Work office/branch location (optional)', max_length=255, null=True, verbose_name='Work Location'),
        ),
    ]
