# Generated by Django 5.0.2 on 2025-11-26 04:59
# Generated by Django 4.2.7 on 2025-11-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_employee_aadhar_number_employee_duty_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Employee photo/avatar', null=True, upload_to='employees/avatars/'),
        ),
    ]
