# Generated by Django 5.0.2 on 2025-12-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Employee contact number (WhatsApp enabled)', max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
