# Generated by Django 4.2.7 on 2025-12-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Employee contact number (WhatsApp enabled)', max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
