# Generated by Django 4.2.7 on 2025-12-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0007_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Residential address', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.CharField(blank=True, help_text='District', max_length=255, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of employee', max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization name', max_length=255, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(blank=True, help_text='Personal phone number', max_length=20, null=True, verbose_name='Personal Phone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place',
            field=models.CharField(blank=True, help_text='Place/City', max_length=255, null=True, verbose_name='Place'),
        ),
        migrations.AddField(
            model_name='employee',
            name='residential_phone',
            field=models.CharField(blank=True, help_text='Residential phone number', max_length=20, null=True, verbose_name='Residential Phone'),
        ),
    ]
