# Generated by Django 5.2.7 on 2026-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0009_employee_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='uan_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='UAN Number'),
        ),
    ]
