# Generated by Django 5.2.7 on 2026-05-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_management', '0003_department_jobtitle_department'),
        ('employee_management', '0010_employee_uan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(blank=True, help_text='Departments this employee belongs to', related_name='employees', to='cv_management.department'),
        ),
    ]
