# Generated by Django 5.2.7 on 2026-04-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetask',
            name='completed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousetask',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
