# Generated by Django 5.0.2 on 2026-01-20 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Admin name for reference', max_length=100)),
                ('phone_number', models.CharField(help_text='Phone number with country code (e.g., +918281561081)', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('hr_admin', 'HR Admin'), ('manager', 'Manager'), ('payroll_admin', 'Payroll Admin'), ('global_cc', 'Global CC')], help_text='Admin role for routing notifications', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Receive notifications')),
                ('is_api_sender', models.BooleanField(default=False, help_text='Mark as API sender number (will be excluded from notifications)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Number',
                'verbose_name_plural': 'Admin Numbers',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('punch_in', 'Punch In'), ('punch_out', 'Punch Out'), ('leave_request', 'Leave Request'), ('leave_approval', 'Leave Approval'), ('leave_rejection', 'Leave Rejection'), ('late_request', 'Late Request'), ('late_approval', 'Late Approval'), ('late_rejection', 'Late Rejection'), ('early_request', 'Early Request'), ('early_approval', 'Early Approval'), ('early_rejection', 'Early Rejection'), ('generic_notification', 'Generic Notification')], help_text='Type of notification', max_length=30, unique=True)),
                ('recipient_type', models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin/HR'), ('both', 'Both')], default='both', help_text='Who receives this template', max_length=10)),
                ('template_text', models.TextField(help_text='Message template. Available variables: {employee_name}, {action}, {date}, {time}, {location}, {reason}, {days}, {leave_type}, {status}, {approver_name}')),
                ('is_active', models.BooleanField(default=True, help_text='Use this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('dxing', 'DXING'), ('twilio', 'Twilio'), ('meta', 'Meta Cloud API')], default='dxing', help_text='WhatsApp service provider', max_length=20)),
                ('api_url', models.URLField(default='https://app.dxing.in/api/send/whatsapp', help_text='API endpoint URL', max_length=500)),
                ('api_secret', models.CharField(help_text='API Secret Key', max_length=500)),
                ('account_id', models.CharField(help_text='Account ID', max_length=500)),
                ('default_priority', models.IntegerField(default=1, help_text='Default message priority (1-10)')),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configurations',
            },
        ),
    ]
