# Generated by Django 5.0.2 on 2026-01-29 09:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(help_text='Vehicle name or model', max_length=255, verbose_name='Vehicle Name')),
                ('company', models.CharField(blank=True, help_text='Vehicle manufacturer/company', max_length=128, null=True, verbose_name='Company/Brand')),
                ('registration_number', models.CharField(help_text='Vehicle registration/license plate number', max_length=64, unique=True, verbose_name='Registration Number')),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike'), ('van', 'Van'), ('truck', 'Truck'), ('bus', 'Bus'), ('other', 'Other')], default='car', max_length=64, null=True, verbose_name='Vehicle Type')),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG')], max_length=64, null=True, verbose_name='Fuel Type')),
                ('color', models.CharField(blank=True, max_length=64, null=True, verbose_name='Color')),
                ('manufacturing_year', models.IntegerField(blank=True, null=True, verbose_name='Manufacturing Year')),
                ('seating_capacity', models.IntegerField(blank=True, null=True, verbose_name='Seating Capacity')),
                ('photo', models.ImageField(blank=True, help_text='Vehicle photo', null=True, upload_to='vehicles/photos/', verbose_name='Vehicle Photo')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Name')),
                ('insurance_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Insurance Number')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True, verbose_name='Insurance Expiry Date')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Last Service Date')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Next Service Date')),
                ('current_odometer', models.DecimalField(decimal_places=2, default=0.0, help_text='Current odometer reading in KM', max_digits=10, verbose_name='Current Odometer (KM)')),
                ('chassis_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Chassis Number')),
                ('engine_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Engine Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, help_text='Is vehicle currently active/available', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle_management_vehicle',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Trip Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('time_period', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2, verbose_name='Time Period (AM/PM)')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Name')),
                ('purpose', models.TextField(verbose_name='Purpose of Trip')),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fuel Cost (₹)')),
                ('odometer_start', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Odometer Start (KM)')),
                ('odometer_start_image', models.ImageField(blank=True, null=True, upload_to='trips/odometer_start/', verbose_name='Odometer Start Image')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('odometer_end', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Odometer End (KM)')),
                ('odometer_end_image', models.ImageField(blank=True, null=True, upload_to='trips/odometer_end/', verbose_name='Odometer End Image')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated from odometer readings', max_digits=10, null=True, verbose_name='Distance (KM)')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated from start and end time', max_digits=6, null=True, verbose_name='Duration (Hours)')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='started', max_length=32, verbose_name='Trip Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes/Remarks')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trips', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('employee', models.ForeignKey(help_text='Employee who is making the trip', on_delete=django.db.models.deletion.PROTECT, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Employee/Traveled By')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicle_management.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'vehicle_management_trip',
                'ordering': ['-created_at'],
            },
        ),
    ]
