# Generated by Django 5.0.2 on 2026-01-30 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_date', models.DateField(help_text='Date when the violation occurred', verbose_name='Detail Date')),
                ('challan_number', models.CharField(help_text='Unique challan/ticket number', max_length=128, unique=True, verbose_name='Challan Number')),
                ('challan_date', models.DateField(help_text='Date when the challan was issued', verbose_name='Challan Date')),
                ('offence_type', models.CharField(help_text='Type of traffic violation (e.g., Speeding, Parking, Red Light)', max_length=255, verbose_name='Offence Type')),
                ('location', models.CharField(help_text='Location where the violation occurred', max_length=255, verbose_name='Location')),
                ('fine_amount', models.DecimalField(decimal_places=2, help_text='Amount of fine to be paid', max_digits=10, verbose_name='Fine Amount (₹)')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=32, verbose_name='Payment Status')),
                ('payment_date', models.DateField(blank=True, help_text='Date when the fine was paid', null=True, verbose_name='Payment Date')),
                ('remarks', models.TextField(blank=True, help_text='Any additional notes or comments', null=True, verbose_name='Remarks/Notes')),
                ('challan_document', models.FileField(blank=True, help_text='Upload challan receipt/document', null=True, upload_to='challans/documents/', verbose_name='Challan Document')),
                ('payment_receipt', models.FileField(blank=True, help_text='Upload payment receipt if paid', null=True, upload_to='challans/receipts/', verbose_name='Payment Receipt')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challans', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owner', models.ForeignKey(help_text='Owner responsible for the challan', on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_challans', to=settings.AUTH_USER_MODEL, verbose_name='Vehicle Owner')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='vehicle_management.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Challan',
                'verbose_name_plural': 'Vehicle Challans',
                'db_table': 'vehicle_management_challan',
                'ordering': ['-challan_date', '-created_at'],
            },
        ),
    ]
