# Generated by Django 5.2.7 on 2026-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_vehiclechallan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Fuel Cost (₹)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='odometer_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Odometer Start (KM)'),
        ),
    ]
