# Generated by Django 5.2.7 on 2026-02-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0003_alter_trip_fuel_cost_alter_trip_odometer_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='Purpose of Trip'),
        ),
    ]
