# Generated by Django 5.2.7 on 2026-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0004_alter_trip_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.CharField(blank=True, help_text='Route taken for the trip (e.g. City A → City B)', max_length=512, null=True, verbose_name='Route'),
        ),
    ]
