# Generated by Django 5.2.7 on 2026-03-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0005_add_route_to_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='maintenance_air_checking',
            field=models.BooleanField(default=False, help_text='Air pressure checking done during trip', verbose_name='Air Checking'),
        ),
        migrations.AddField(
            model_name='trip',
            name='maintenance_alignment',
            field=models.BooleanField(default=False, help_text='Wheel alignment done during trip', verbose_name='Alignment'),
        ),
        migrations.AddField(
            model_name='trip',
            name='maintenance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Maintenance Cost (₹)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='maintenance_grease_oil',
            field=models.BooleanField(default=False, help_text='Grease oil check/replacement done during trip', verbose_name='Grease Oil'),
        ),
        migrations.AddField(
            model_name='trip',
            name='maintenance_washing',
            field=models.BooleanField(default=False, help_text='Vehicle washing done during trip', verbose_name='Washing'),
        ),
    ]
