# Generated by ChatGPT on 2026-03-19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0006_add_maintenance_cost_to_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ownership_type',
            field=models.CharField(
                choices=[('company', 'Company'), ('private', 'Private')],
                default='company',
                help_text='Whether the vehicle is company owned or private',
                max_length=32,
                verbose_name='Ownership Type',
            ),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_expiry_date',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Pollution Expiry Date',
            ),
        ),
    ]
