# Generated by Django 5.2.7 on 2026-04-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0007_vehicle_ownership_pollution'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='invoice_bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/invoice_bills/', verbose_name='Invoice Bill Image'),
        ),
    ]
