# Generated by Django 5.2.7 on 2026-04-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0008_trip_invoice_bill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='next_service_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Next service due at this KM reading', max_digits=10, null=True, verbose_name='Next Service KM'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permit_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Permit Expiry Date'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tax Expiry Date'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='witness',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Witness'),
        ),
    ]
