# Generated by Django 5.2.7 on 2026-05-15 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0009_vehicle_next_service_km_vehicle_permit_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255, verbose_name='Vehicle Name')),
                ('vehicle_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Vehicle Number/Registration')),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Driver Name')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('service_center_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Service Center Name')),
                ('odometer_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Odometer Reading (KM)')),
                ('engine_oil_change', models.BooleanField(default=False, verbose_name='Engine Oil Change')),
                ('tyre_replacement', models.BooleanField(default=False, verbose_name='Tyre Replacement')),
                ('battery_replacement', models.BooleanField(default=False, verbose_name='Battery Replacement')),
                ('brake_service', models.BooleanField(default=False, verbose_name='Brake Service')),
                ('insurance_renewal', models.BooleanField(default=False, verbose_name='Insurance Renewal')),
                ('puc_renewal', models.BooleanField(default=False, verbose_name='PUC Renewal')),
                ('road_tax_renewal', models.BooleanField(default=False, verbose_name='Road Tax Renewal')),
                ('general_repair', models.BooleanField(default=False, verbose_name='General Repair')),
                ('fuel_expense', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Fuel Expense (₹)')),
                ('spare_parts_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Spare Parts Cost (₹)')),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Maintenance Cost (₹)')),
                ('next_service_due_date', models.DateField(blank=True, null=True, verbose_name='Next Service Due Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks / Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Vehicle Maintenance',
                'verbose_name_plural': 'Vehicle Maintenance Records',
                'db_table': 'vehicle_management_maintenance',
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
