# Generated by Django 5.2.7 on 2026-05-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0010_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='fuel_expense',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_cost',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='spare_parts_cost',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Service Date'),
        ),
    ]
