# Generated by Django 5.2.7 on 2026-05-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0011_remove_maintenance_fuel_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_images/', verbose_name='Maintenance Image'),
        ),
    ]
