# Generated by Django 4.2.7 on 2026-01-12 06:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Attendance date')),
                ('first_punch_in_time', models.DateTimeField(blank=True, null=True)),
                ('first_punch_in_location', models.CharField(blank=True, max_length=255, null=True)),
                ('first_punch_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('first_punch_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('last_punch_out_location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_punch_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_punch_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('total_working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('total_break_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('is_currently_on_break', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day'), ('leave', 'Leave'), ('casual_leave', 'Casual Leave (Paid)'), ('sick_leave', 'Sick Leave (Paid)'), ('special_leave', 'Special Leave (Paid)'), ('unpaid_leave', 'Unpaid Leave'), ('mandatory_holiday', 'Mandatory Holiday (Paid)'), ('special_holiday', 'Special Holiday (Paid)'), ('sunday', 'Sunday (Paid)'), ('wfh', 'Work From Home')], default='half', max_length=20)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], default='unverified', max_length=15)),
                ('is_sunday', models.BooleanField(default=False, help_text='Automatically marked as Sunday')),
                ('is_holiday', models.BooleanField(default=False, help_text='Holiday day')),
                ('is_paid_leave', models.BooleanField(default=False, help_text='Whether this is a paid leave day')),
                ('leave_type', models.CharField(blank=True, help_text='Type of leave if applicable', max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'hr_attendance',
                'ordering': ['-date', '-first_punch_in_time'],
            },
        ),
        migrations.CreateModel(
            name='LeaveMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(help_text='Name of the leave (e.g., Diwali, Christmas)', max_length=200)),
                ('leave_date', models.DateField(blank=True, help_text='Specific date for the leave (optional)', null=True)),
                ('category', models.CharField(choices=[('festival', 'Festival Leave'), ('national', 'National Holiday'), ('company', 'Company Holiday'), ('special', 'Special Leave'), ('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('earned', 'Earned Leave'), ('emergency', 'Emergency Leave'), ('unpaid', 'Unpaid Leave'), ('mandatory_holiday', 'Mandatory Holiday')], default='special', help_text='Category of leave', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid Leave'), ('unpaid', 'Unpaid Leave')], default='paid', help_text='Whether this leave is paid or unpaid', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of the leave', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this leave type is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this leave type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_masters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Master',
                'verbose_name_plural': 'Leave Masters',
                'db_table': 'hr_leave_master',
                'ordering': ['leave_date', 'leave_name'],
            },
        ),
        migrations.CreateModel(
            name='PunchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_type', models.CharField(choices=[('in', 'Punch In'), ('out', 'Punch Out')], max_length=3)),
                ('punch_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_records', to='HR.attendance')),
            ],
            options={
                'verbose_name': 'Punch Record',
                'verbose_name_plural': 'Punch Records',
                'db_table': 'hr_punch_record',
                'ordering': ['punch_time'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave (Paid)'), ('sick', 'Sick Leave (Paid)'), ('special', 'Special Leave (Paid)'), ('unpaid', 'Unpaid Leave'), ('emergency', 'Emergency Leave'), ('earned', 'Earned Leave'), ('leave_master', 'Leave Master Type')], help_text='Type of leave', max_length=20)),
                ('from_date', models.DateField(help_text='Leave start date')),
                ('to_date', models.DateField(help_text='Leave end date')),
                ('reason', models.TextField(help_text='Reason for leave')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Leave request status', max_length=10)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this leave is paid or unpaid')),
                ('deducted_from_balance', models.BooleanField(default=False, help_text='Whether leave has been deducted from balance')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_master', models.ForeignKey(blank=True, help_text='Leave Master entry if this request is based on a predefined leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='HR.leavemaster')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting leave', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'db_table': 'hr_leave_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('late_by_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_late_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Late Request',
                'verbose_name_plural': 'Late Requests',
                'db_table': 'hr_late_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Holiday name', max_length=200)),
                ('date', models.DateField(help_text='Holiday date', unique=True)),
                ('holiday_type', models.CharField(choices=[('mandatory', 'Mandatory Holiday (Paid)'), ('special', 'Special Holiday (Paid)'), ('optional', 'Optional Holiday')], default='special', help_text='Type of holiday', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Holiday description', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether employees get paid for this holiday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='HR/Manager who created this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'hr_holiday',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='holiday',
            field=models.ForeignKey(blank=True, help_text='Associated holiday if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='HR.holiday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(help_text='User/Employee', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave_balance', models.DecimalField(decimal_places=2, default=0, help_text='Casual leave balance (accumulates monthly)', max_digits=5)),
                ('casual_leave_used', models.DecimalField(decimal_places=2, default=0, help_text='Casual leave used this year', max_digits=5)),
                ('sick_leave_balance', models.IntegerField(default=3, help_text='Sick leave balance for the year')),
                ('sick_leave_used', models.IntegerField(default=0, help_text='Sick leave used this year')),
                ('special_leave_balance', models.IntegerField(default=7, help_text='Special leave balance for the year')),
                ('special_leave_used', models.IntegerField(default=0, help_text='Special leave used this year')),
                ('unpaid_leave_taken', models.DecimalField(decimal_places=2, default=0, help_text='Total unpaid leave taken this year', max_digits=5)),
                ('year', models.IntegerField(default=2026)),
                ('last_casual_credit_month', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Leave Balance',
                'verbose_name_plural': 'Employee Leave Balances',
                'db_table': 'hr_employee_leave_balance',
                'unique_together': {('user', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EarlyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('early_by_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_early_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Early Request',
                'verbose_name_plural': 'Early Requests',
                'db_table': 'hr_early_request',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'date'], name='hr_attendan_user_id_cb0644_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='hr_attendan_date_3a46d7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['verification_status'], name='hr_attendan_verific_3abadb_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_sunday'], name='hr_attendan_is_sund_6f4794_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_holiday'], name='hr_attendan_is_holi_067090_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'date')},
        ),
    ]
