# Generated by Django 5.0.2 on 2025-11-04 05:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Holiday name', max_length=200)),
                ('date', models.DateField(help_text='Holiday date', unique=True)),
                ('description', models.TextField(blank=True, help_text='Holiday description', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'hr_holiday',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('unpaid', 'Unpaid Leave'), ('emergency', 'Emergency Leave')], help_text='Type of leave', max_length=20)),
                ('from_date', models.DateField(help_text='Leave start date')),
                ('to_date', models.DateField(help_text='Leave end date')),
                ('reason', models.TextField(help_text='Reason for leave')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Leave request status', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting leave', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'db_table': 'hr_leave_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Attendance date')),
                ('punch_in_time', models.DateTimeField(blank=True, help_text='Punch in timestamp', null=True)),
                ('punch_out_time', models.DateTimeField(blank=True, help_text='Punch out timestamp', null=True)),
                ('punch_in_location', models.CharField(blank=True, help_text='Punch in location name', max_length=255, null=True)),
                ('punch_out_location', models.CharField(blank=True, help_text='Punch out location name', max_length=255, null=True)),
                ('punch_in_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Punch in latitude', max_digits=10, null=True)),
                ('punch_in_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Punch in longitude', max_digits=10, null=True)),
                ('punch_out_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Punch out latitude', max_digits=10, null=True)),
                ('punch_out_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Punch out longitude', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day'), ('leave', 'Leave'), ('wfh', 'Work From Home')], default='full', help_text='Attendance status', max_length=10)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], default='unverified', help_text='Verification status by admin', max_length=15)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total working hours', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('note', models.TextField(blank=True, help_text='Employee note', null=True)),
                ('admin_note', models.TextField(blank=True, help_text='Admin/HR note', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Verification timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User/Employee', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified the attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'hr_attendance',
                'ordering': ['-date', '-punch_in_time'],
                'indexes': [models.Index(fields=['user', 'date'], name='hr_attendan_user_id_cb0644_idx'), models.Index(fields=['date'], name='hr_attendan_date_3a46d7_idx'), models.Index(fields=['verification_status'], name='hr_attendan_verific_3abadb_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
