# Generated by Django 5.0.2 on 2025-12-10 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='holiday',
            field=models.ForeignKey(blank=True, help_text='Associated holiday if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='HR.holiday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='Holiday day'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_sunday',
            field=models.BooleanField(default=False, help_text='Automatically marked as Sunday'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='HR/Manager who created this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Whether employees get paid for this holiday'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day'), ('leave', 'Leave'), ('casual_leave', 'Casual Leave (Paid)'), ('sick_leave', 'Sick Leave (Paid)'), ('special_leave', 'Special Leave (Paid)'), ('unpaid_leave', 'Unpaid Leave'), ('mandatory_holiday', 'Mandatory Holiday (Paid)'), ('special_holiday', 'Special Holiday (Paid)'), ('sunday', 'Sunday (Paid)'), ('wfh', 'Work From Home')], default='half', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_sunday'], name='hr_attendan_is_sund_6f4794_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_holiday'], name='hr_attendan_is_holi_067090_idx'),
        ),
    ]
