# Generated by Django 5.0.2 on 2026-01-21 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
        ('master', '0003_alter_leavemaster_options_alter_leavemaster_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemaster',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_master',
            field=models.ForeignKey(default=2, help_text='Leave type from Leave Master', on_delete=django.db.models.deletion.PROTECT, related_name='hr_leave_requests', to='master.leavemaster'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_paid_leave',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_leave',
            field=models.BooleanField(default=False, help_text='Whether this day is a leave day'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_paid_day',
            field=models.BooleanField(default=True, help_text='For payroll: whether this day is paid'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_master',
            field=models.ForeignKey(blank=True, help_text='Leave type from master if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='master.leavemaster'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_request',
            field=models.ForeignKey(blank=True, help_text='Associated leave request if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='HR.leaverequest'),
        ),
        migrations.AddField(
            model_name='earlyrequest',
            name='leave_master',
            field=models.ForeignKey(blank=True, help_text='Leave type for early departure (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hr_early_requests', to='master.leavemaster'),
        ),
        migrations.AddField(
            model_name='laterequest',
            name='leave_master',
            field=models.ForeignKey(blank=True, help_text='Leave type for late arrival (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hr_late_requests', to='master.leavemaster'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day'), ('leave', 'Leave'), ('wfh', 'Work From Home'), ('sunday', 'Sunday (Paid)'), ('holiday', 'Holiday (Paid)')], default='half', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Auto-set from Leave Master payment status'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_leave'], name='hr_attendan_is_leav_d864a7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_paid_day'], name='hr_attendan_is_paid_fca9a6_idx'),
        ),
        migrations.DeleteModel(
            name='LeaveMaster',
        ),
    ]
