# Generated by Django 5.0.2 on 2025-11-12 05:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_break'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of early departure')),
                ('early_by_minutes', models.IntegerField(help_text='How many minutes early', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('reason', models.TextField(help_text='Reason for early departure')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Request status', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_early_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting early departure', on_delete=django.db.models.deletion.CASCADE, related_name='early_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Early Request',
                'verbose_name_plural': 'Early Requests',
                'db_table': 'hr_early_request',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of late arrival')),
                ('late_by_minutes', models.IntegerField(help_text='How many minutes late', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('reason', models.TextField(help_text='Reason for late arrival')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Request status', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_late_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting late arrival', on_delete=django.db.models.deletion.CASCADE, related_name='late_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Late Request',
                'verbose_name_plural': 'Late Requests',
                'db_table': 'hr_late_request',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
