# Generated by Django 5.0.2 on 2025-12-15 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_attendance_holiday_attendance_is_holiday_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave (Paid)'), ('sick', 'Sick Leave (Paid)'), ('special', 'Special Leave (Paid)'), ('unpaid', 'Unpaid Leave'), ('emergency', 'Emergency Leave'), ('leave_master', 'Leave Master Type')], help_text='Type of leave', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(help_text='Name of the leave (e.g., Diwali, Christmas)', max_length=200)),
                ('leave_date', models.DateField(blank=True, help_text='Specific date for the leave (optional)', null=True)),
                ('category', models.CharField(choices=[('festival', 'Festival Leave'), ('national', 'National Holiday'), ('company', 'Company Holiday'), ('special', 'Special Leave')], default='special', help_text='Category of leave', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid Leave'), ('unpaid', 'Unpaid Leave')], default='paid', help_text='Whether this leave is paid or unpaid', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of the leave', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this leave type is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this leave type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_masters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Master',
                'verbose_name_plural': 'Leave Masters',
                'db_table': 'hr_leave_master',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_master',
            field=models.ForeignKey(blank=True, help_text='Leave Master entry if this request is based on a predefined leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='HR.leavemaster'),
        ),
    ]
