# Generated by Django 5.0.2 on 2026-01-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_remove_leavemaster_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(blank=True, help_text='Deprecated - use leave_master instead', max_length=50, null=True),
        ),
    ]
