# Generated by Django 5.0.2 on 2025-12-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_alter_leaverequest_leave_type_leavemaster_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavemaster',
            options={},
        ),
        migrations.RemoveField(
            model_name='leavemaster',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leavemaster',
            name='description',
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='category',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('special', 'Special Leave'), ('mandatory_holiday', 'Mandatory Holiday')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='leave_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='leavemaster',
            table=None,
        ),
    ]
