# Generated by Django 5.0.2 on 2026-01-22 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_leaverequest_leave_type'),
        ('master', '0003_alter_leavemaster_options_alter_leavemaster_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_leave_requests', to='master.leavemaster'),
        ),
    ]
