# Generated by Django 5.0.2 on 2025-12-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_attendancebreak'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laterequest',
            unique_together=set(),
        ),
    ]
