# Generated by Django 5.0.2 on 2025-12-17 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_alter_leavemaster_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavemaster',
            options={'ordering': ['-created_at'], 'verbose_name': 'Leave Master', 'verbose_name_plural': 'Leave Masters'},
        ),
        migrations.AddField(
            model_name='leavemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this leave type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_masters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavemaster',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the leave', null=True),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='category',
            field=models.CharField(choices=[('festival', 'Festival Leave'), ('national', 'National Holiday'), ('company', 'Company Holiday'), ('special', 'Special Leave')], default='special', help_text='Category of leave', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this leave type is currently active'),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='leave_date',
            field=models.DateField(blank=True, help_text='Specific date for the leave (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='leave_name',
            field=models.CharField(help_text='Name of the leave (e.g., Diwali, Christmas)', max_length=200),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid Leave'), ('unpaid', 'Unpaid Leave')], default='paid', help_text='Whether this leave is paid or unpaid', max_length=10),
        ),
        migrations.AlterModelTable(
            name='leavemaster',
            table='hr_leave_master',
        ),
    ]
