# Generated by Django 5.0.2 on 2026-01-22 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_alter_leaverequest_leave_master'),
        ('master', '0005_alter_leavemaster_options_alter_leavemaster_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_master',
            field=models.ForeignKey(db_column='leave_master_id', on_delete=django.db.models.deletion.PROTECT, related_name='hr_leave_requests', to='master.leavemaster'),
        ),
    ]
