# Generated by Django 5.0.2 on 2025-12-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_alter_leavemaster_options_leavemaster_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemaster',
            name='category',
            field=models.CharField(choices=[('festival', 'Festival Leave'), ('national', 'National Holiday'), ('company', 'Company Holiday'), ('special', 'Special Leave'), ('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('earned', 'Earned Leave'), ('emergency', 'Emergency Leave'), ('unpaid', 'Unpaid Leave')], default='special', help_text='Category of leave', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave (Paid)'), ('sick', 'Sick Leave (Paid)'), ('special', 'Special Leave (Paid)'), ('unpaid', 'Unpaid Leave'), ('emergency', 'Emergency Leave'), ('earned', 'Earned Leave'), ('leave_master', 'Leave Master Type')], help_text='Type of leave', max_length=20),
        ),
    ]
