# Generated by Django 5.0.2 on 2026-01-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_alter_leaverequest_leave_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earlyrequest',
            name='leave_master',
        ),
        migrations.RemoveField(
            model_name='laterequest',
            name='leave_master',
        ),
    ]
