# Generated by Django 4.2.7 on 2025-12-05 05:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_alter_laterequest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_type', models.CharField(choices=[('in', 'Punch In'), ('out', 'Punch Out')], help_text='Type of punch (in/out)', max_length=3)),
                ('punch_time', models.DateTimeField(help_text='Punch timestamp')),
                ('location', models.CharField(blank=True, help_text='Punch location', max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude', max_digits=10, null=True)),
                ('note', models.TextField(blank=True, help_text='Note for this punch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Punch Record',
                'verbose_name_plural': 'Punch Records',
                'db_table': 'hr_punch_record',
                'ordering': ['punch_time'],
            },
        ),
        migrations.RemoveField(
            model_name='break',
            name='attendance',
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-first_punch_in_time'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_longitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_longitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_punch_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='First punch in latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_punch_in_location',
            field=models.CharField(blank=True, help_text='First punch in location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_punch_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='First punch in longitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_punch_in_time',
            field=models.DateTimeField(blank=True, help_text='First punch in timestamp (start of day)', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_currently_on_break',
            field=models.BooleanField(default=False, help_text='Whether user is currently on break'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_punch_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Last punch out latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_punch_out_location',
            field=models.CharField(blank=True, help_text='Last punch out location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_punch_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Last punch out longitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_punch_out_time',
            field=models.DateTimeField(blank=True, help_text='Last punch out timestamp (end of day)', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_break_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total break hours', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_working_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total working hours (excluding breaks)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day'), ('leave', 'Leave'), ('wfh', 'Work From Home')], default='half', help_text='Attendance status', max_length=10),
        ),
        migrations.DeleteModel(
            name='AttendanceBreak',
        ),
        migrations.DeleteModel(
            name='Break',
        ),
        migrations.AddField(
            model_name='punchrecord',
            name='attendance',
            field=models.ForeignKey(help_text='Related attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='punch_records', to='HR.attendance'),
        ),
        migrations.AddIndex(
            model_name='punchrecord',
            index=models.Index(fields=['attendance', 'punch_time'], name='hr_punch_re_attenda_fc5bfe_idx'),
        ),
    ]
