# Generated by Django 5.0.2 on 2026-01-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_remove_earlyrequest_leave_master_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='earlyrequest',
            unique_together=set(),
        ),
    ]
