# Generated by Django 4.2.7 on 2026-01-08 07:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0006_punchrecord_remove_break_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave_balance', models.DecimalField(decimal_places=2, default=0, help_text='Casual leave balance (accumulates monthly)', max_digits=5)),
                ('casual_leave_used', models.DecimalField(decimal_places=2, default=0, help_text='Casual leave used this year', max_digits=5)),
                ('sick_leave_balance', models.IntegerField(default=3, help_text='Sick leave balance for the year')),
                ('sick_leave_used', models.IntegerField(default=0, help_text='Sick leave used this year')),
                ('special_leave_balance', models.IntegerField(default=7, help_text='Special leave balance for the year')),
                ('special_leave_used', models.IntegerField(default=0, help_text='Special leave used this year')),
                ('unpaid_leave_taken', models.DecimalField(decimal_places=2, default=0, help_text='Total unpaid leave taken this year', max_digits=5)),
                ('year', models.IntegerField(default=2026)),
                ('last_casual_credit_month', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Leave Balance',
                'verbose_name_plural': 'Employee Leave Balances',
                'db_table': 'hr_employee_leave_balance',
            },
        ),
        migrations.CreateModel(
            name='LeaveMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(help_text='Name of the leave (e.g., Diwali, Christmas)', max_length=200)),
                ('leave_date', models.DateField(blank=True, help_text='Specific date for the leave (optional)', null=True)),
                ('category', models.CharField(choices=[('festival', 'Festival Leave'), ('national', 'National Holiday'), ('company', 'Company Holiday'), ('special', 'Special Leave'), ('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('earned', 'Earned Leave'), ('emergency', 'Emergency Leave'), ('unpaid', 'Unpaid Leave'), ('mandatory_holiday', 'Mandatory Holiday')], default='special', help_text='Category of leave', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid Leave'), ('unpaid', 'Unpaid Leave')], default='paid', help_text='Whether this leave is paid or unpaid', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of the leave', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this leave type is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Master',
                'verbose_name_plural': 'Leave Masters',
                'db_table': 'hr_leave_master',
                'ordering': ['leave_date', 'leave_name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='punchrecord',
            name='hr_punch_re_attenda_fc5bfe_idx',
        ),
        migrations.AddField(
            model_name='attendance',
            name='holiday',
            field=models.ForeignKey(blank=True, help_text='Associated holiday if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='HR.holiday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='Holiday day'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_paid_leave',
            field=models.BooleanField(default=False, help_text='Whether this is a paid leave day'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_sunday',
            field=models.BooleanField(default=False, help_text='Automatically marked as Sunday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(blank=True, help_text='Type of leave if applicable', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='HR/Manager who created this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('mandatory', 'Mandatory Holiday (Paid)'), ('special', 'Special Holiday (Paid)'), ('optional', 'Optional Holiday')], default='special', help_text='Type of holiday', max_length=20),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Whether employees get paid for this holiday'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='deducted_from_balance',
            field=models.BooleanField(default=False, help_text='Whether leave has been deducted from balance'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Whether this leave is paid or unpaid'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_punch_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_punch_in_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_punch_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_punch_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_currently_on_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_punch_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_punch_out_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_punch_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_punch_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day'), ('leave', 'Leave'), ('casual_leave', 'Casual Leave (Paid)'), ('sick_leave', 'Sick Leave (Paid)'), ('special_leave', 'Special Leave (Paid)'), ('unpaid_leave', 'Unpaid Leave'), ('mandatory_holiday', 'Mandatory Holiday (Paid)'), ('special_holiday', 'Special Holiday (Paid)'), ('sunday', 'Sunday (Paid)'), ('wfh', 'Work From Home')], default='half', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_break_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], default='unverified', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='earlyrequest',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='earlyrequest',
            name='early_by_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AlterField(
            model_name='earlyrequest',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='earlyrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_early_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='earlyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='earlyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laterequest',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='laterequest',
            name='late_by_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AlterField(
            model_name='laterequest',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laterequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_late_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='laterequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave (Paid)'), ('sick', 'Sick Leave (Paid)'), ('special', 'Special Leave (Paid)'), ('unpaid', 'Unpaid Leave'), ('emergency', 'Emergency Leave'), ('earned', 'Earned Leave'), ('leave_master', 'Leave Master Type')], help_text='Type of leave', max_length=20),
        ),
        migrations.AlterField(
            model_name='punchrecord',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_records', to='HR.attendance'),
        ),
        migrations.AlterField(
            model_name='punchrecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='punchrecord',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='punchrecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='punchrecord',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punchrecord',
            name='punch_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='punchrecord',
            name='punch_type',
            field=models.CharField(choices=[('in', 'Punch In'), ('out', 'Punch Out')], max_length=3),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_sunday'], name='hr_attendan_is_sund_6f4794_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_holiday'], name='hr_attendan_is_holi_067090_idx'),
        ),
        migrations.AddField(
            model_name='leavemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this leave type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_masters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_master',
            field=models.ForeignKey(blank=True, help_text='Leave Master entry if this request is based on a predefined leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='HR.leavemaster'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeleavebalance',
            unique_together={('user', 'year')},
        ),
    ]
