# Generated by Django 5.0.2 on 2026-01-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_rename_hr_attendan_is_paid_fca9a6_idx_hr_attendan_is_paid_c97b6c_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='hr_attendan_is_paid_fca9a6_idx',
            old_name='hr_attendan_is_paid_c97b6c_idx',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_paid_day',
            field=models.BooleanField(default=True, help_text='For payroll: whether this day is paid'),
        ),
    ]
