# Generated by Django 5.0.2 on 2026-01-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_rename_hr_attendan_is_paid_c97b6c_idx_hr_attendan_is_paid_fca9a6_idx_and_more'),
    ]

    operations = [
    ]
