# Generated by Django 5.0.2 on 2026-01-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0011_rename_is_paid_leave_column'),
        ('master', '0005_alter_leavemaster_options_alter_leavemaster_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='HR.holiday'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='master.leavemaster'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='HR.leaverequest'),
        ),
    ]
