# Generated by Django 5.2.7 on 2026-01-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0012_alter_attendance_holiday_alter_attendance_is_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day'), ('leave', 'Leave'), ('wfh', 'Work From Home'), ('sunday', 'Sunday (Paid)'), ('holiday', 'Holiday (Paid)'), ('special_leave', 'Special Leave'), ('mandatory_holiday', 'Mandatory Holiday')], default='half', max_length=20),
        ),
    ]
