# Generated by Django 5.0.2 on 2026-01-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0013_alter_attendance_status'),
        ('master', '0006_alter_leavemaster_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_master',
            field=models.ForeignKey(help_text='Reference to leave type in master app', on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='master.leavemaster'),
        ),
    ]
