# Generated by Django 5.0.2 on 2026-01-28 12:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0014_alter_leaverequest_leave_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Office name (e.g., "Main Office", "Branch Office")', max_length=200)),
                ('address', models.TextField(help_text='Complete office address')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Office latitude (e.g., 11.6112893)', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Office longitude (e.g., 76.0840294)', max_digits=10)),
                ('geofence_radius_meters', models.IntegerField(default=50, help_text='Allowed radius in meters (10-500m). Recommended: 50-100m', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)])),
                ('is_active', models.BooleanField(default=True, help_text='Only one office location should be active at a time')),
                ('detection_method', models.CharField(choices=[('gps', 'GPS Detection'), ('manual', 'Manual Entry'), ('map', 'Map Selection')], default='gps', help_text='How this location was configured', max_length=20)),
                ('gps_accuracy_meters', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy when location was detected', max_digits=6, null=True)),
                ('configured_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this location', null=True)),
                ('configured_by', models.ForeignKey(blank=True, help_text='Admin who configured this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_offices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Location',
                'verbose_name_plural': 'Office Locations',
                'db_table': 'hr_office_location',
                'ordering': ['-is_active', '-configured_at'],
            },
        ),
    ]
