# Generated by Django 5.0.2 on 2026-03-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0015_officelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_working_sunday',
            field=models.BooleanField(default=False, help_text='Admin-marked: this Sunday is treated as a regular working day'),
        ),
    ]
