# Generated by Django 5.0.2 on 2026-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0016_attendance_is_working_sunday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day'), ('absent', 'Absent'), ('leave', 'Leave'), ('wfh', 'Work From Home'), ('sunday', 'Sunday (Paid)'), ('holiday', 'Holiday (Paid)'), ('special_leave', 'Special Leave'), ('mandatory_holiday', 'Mandatory Holiday')], default='half', max_length=20),
        ),
    ]
