# Generated by Django 5.2.7 on 2026-06-08 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0017_alter_attendance_status'),
        ('cv_management', '0003_department_jobtitle_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Parameter name (e.g., "Emergency Contact", "Blood Group")', max_length=255)),
                ('input_type', models.CharField(choices=[('manual', 'Manual Entry'), ('dropdown', 'Dropdown Selection'), ('checkbox', 'Checkbox'), ('date', 'Date Picker'), ('number', 'Number'), ('text', 'Text')], default='manual', help_text='Type of input field for this parameter', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this parameter is for', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this parameter is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this parameter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parameters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'db_table': 'hr_parameters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParameterDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_parameters', to='cv_management.department')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_departments', to='HR.parameter')),
            ],
            options={
                'verbose_name': 'Parameter Department',
                'verbose_name_plural': 'Parameter Departments',
                'db_table': 'hr_parameter_departments',
                'ordering': ['parameter', 'department'],
                'unique_together': {('parameter', 'department')},
            },
        ),
    ]
