# Generated by Django 5.2.7 on 2026-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0018_parameter_parameterdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='dept_params',
            field=models.JSONField(blank=True, default=dict, help_text='Parameter rows with price/value per target management department'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='target_dept_keys',
            field=models.JSONField(blank=True, default=list, help_text='Target management department keys this parameter applies to'),
        ),
    ]
