# Generated by Django 5.0.2 on 2025-12-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(help_text='e.g., New Year, Christmas, Annual Leave', max_length=100)),
                ('leave_date', models.DateField(help_text='Date of the leave/holiday')),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='paid', max_length=10)),
                ('category', models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('special', 'Special Leave'), ('mandatory_holiday', 'Mandatory Holiday')], max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this leave type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Master',
                'verbose_name_plural': 'Leave Masters',
                'ordering': ['-leave_date'],
            },
        ),
    ]
