# Generated by Django 4.2.7 on 2026-01-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=100)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('special', 'Special Leave'), ('mandatory_holiday', 'Mandatory Holiday')], max_length=30)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
