# Generated by Django 5.0.2 on 2025-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemaster',
            name='leave_date',
            field=models.DateField(blank=True, help_text='Date of the leave/holiday (optional for ongoing allowances)', null=True),
        ),
    ]
