# Generated by Django 5.0.2 on 2026-01-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_leavemaster_options_alter_leavemaster_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemaster',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the leave type', null=True),
        ),
    ]
