# Generated by Django 5.0.2 on 2026-01-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_leavemaster_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavemaster',
            options={'ordering': ['leave_date', 'leave_name'], 'verbose_name': 'Leave Master', 'verbose_name_plural': 'Leave Masters'},
        ),
        migrations.AlterModelTable(
            name='leavemaster',
            table='hr_leave_master',
        ),
    ]
