# Generated by Django 5.0.2 on 2026-01-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_leavemaster_options_alter_leavemaster_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leavemaster',
            table=None,
        ),
    ]
