# Generated by Django 5.2.7 on 2026-05-21 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_leavemaster_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255, verbose_name='Asset Name')),
                ('asset_id', models.CharField(max_length=128, unique=True, verbose_name='Asset ID')),
                ('asset_category', models.CharField(max_length=128, verbose_name='Asset Category')),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial Number')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Master',
                'verbose_name_plural': 'Asset Masters',
                'db_table': 'master_asset_master',
                'ordering': ['-created_at', 'asset_name'],
            },
        ),
    ]
