# Generated by Django 5.0.2 on 2026-02-06 10:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0008_employee_address_employee_date_of_birth_and_more'),
        ('target_management', '0001_initial'),
        ('vehicle_management', '0002_vehiclechallan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(help_text='Unique delivery number (auto-generated)', max_length=50, unique=True)),
                ('scheduled_date', models.DateField(help_text='Scheduled delivery date')),
                ('scheduled_time', models.TimeField(help_text='Scheduled delivery time')),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Actual delivery start time', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Actual delivery end time', null=True)),
                ('odometer_start', models.DecimalField(blank=True, decimal_places=2, help_text='Odometer reading at start (km)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('odometer_end', models.DecimalField(blank=True, decimal_places=2, help_text='Odometer reading at end (km)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fuel_start', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel level at start (liters)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fuel_end', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel level at end (liters)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_loaded_boxes', models.DecimalField(decimal_places=2, default=0, help_text='Total boxes loaded at start', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_delivered_boxes', models.DecimalField(decimal_places=2, default=0, help_text='Total boxes delivered', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_balance_boxes', models.DecimalField(decimal_places=2, default=0, help_text='Balance boxes returned', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total delivery value', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount collected from customers', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('start_notes', models.TextField(blank=True, help_text='Notes when starting delivery')),
                ('end_notes', models.TextField(blank=True, help_text='Notes when completing delivery')),
                ('remarks', models.TextField(blank=True, help_text='General remarks')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this delivery was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this delivery was last updated')),
                ('completed_by', models.ForeignKey(blank=True, help_text='User who completed this delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deliveries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Delivery person', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='employee_management.employee')),
                ('route', models.ForeignKey(help_text='Delivery route', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='target_management.route')),
                ('vehicle', models.ForeignKey(help_text='Vehicle used for delivery', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='vehicle_management.vehicle')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'delivery_management_delivery',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity loaded at start', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity actually delivered', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Balance quantity returned', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount for this product', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Product-specific notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='delivery_management.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='target_management.product')),
            ],
            options={
                'verbose_name': 'Delivery Product',
                'verbose_name_plural': 'Delivery Products',
                'db_table': 'delivery_management_delivery_product',
                'ordering': ['product__product_name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.PositiveIntegerField(help_text='Order of this stop in the delivery route')),
                ('customer_name', models.CharField(help_text='Customer/Location name', max_length=255)),
                ('customer_address', models.TextField(help_text='Delivery address')),
                ('customer_phone', models.CharField(blank=True, help_text='Customer contact number', max_length=20)),
                ('planned_boxes', models.DecimalField(decimal_places=2, default=0, help_text='Planned boxes for this stop', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivered_boxes', models.DecimalField(decimal_places=2, default=0, help_text='Actually delivered boxes', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, help_text='Planned delivery amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount collected at this stop', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_arrival', models.TimeField(blank=True, help_text='Estimated arrival time', null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, help_text='Actual arrival time', null=True)),
                ('departure_time', models.DateTimeField(blank=True, help_text='Departure time from this stop', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes for this stop')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason if delivery failed/skipped')),
                ('signature_image', models.ImageField(blank=True, help_text='Customer signature', null=True, upload_to='deliveries/signatures/')),
                ('proof_image', models.ImageField(blank=True, help_text='Delivery proof photo', null=True, upload_to='deliveries/proofs/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery_management.delivery')),
            ],
            options={
                'verbose_name': 'Delivery Stop',
                'verbose_name_plural': 'Delivery Stops',
                'db_table': 'delivery_management_delivery_stop',
                'ordering': ['delivery', 'stop_sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_number'], name='delivery_ma_deliver_914d37_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['employee', 'scheduled_date'], name='delivery_ma_employe_57ee41_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['vehicle', 'scheduled_date'], name='delivery_ma_vehicle_cd45c9_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['route', 'scheduled_date'], name='delivery_ma_route_i_80dbf9_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='delivery_ma_status_be1bba_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['scheduled_date'], name='delivery_ma_schedul_ab886b_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['-created_at'], name='delivery_ma_created_33f5a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryproduct',
            unique_together={('delivery', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='deliverystop',
            unique_together={('delivery', 'stop_sequence')},
        ),
    ]
