# Generated by Django 5.0.2 on 2026-02-12 12:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='total_pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total pending/balance amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='balance_boxes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance boxes remaining after this stop', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pending/Balance amount at this stop', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='deliverystop',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash collected at this stop', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='deliverystop',
            name='delivered_boxes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actually delivered boxes at this stop', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
