# Generated by Django 5.2.7 on 2026-02-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0002_delivery_total_pending_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='completion_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude for delivery completion location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='completion_location',
            field=models.CharField(blank=True, help_text='Human-readable completion location description', max_length=500),
        ),
        migrations.AddField(
            model_name='delivery',
            name='completion_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude for delivery completion location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude for delivery start location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='start_location',
            field=models.CharField(blank=True, help_text='Human-readable start location description', max_length=500),
        ),
        migrations.AddField(
            model_name='delivery',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude for delivery start location', max_digits=9, null=True),
        ),
    ]
