# Generated by Django 5.2.7 on 2026-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0003_delivery_completion_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystop',
            name='shop_name',
            field=models.CharField(blank=True, default='', help_text='Shop name entered by delivery person', max_length=255),
        ),
    ]
