# Generated by assistant to add assigned_to field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0004_deliverystop_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='assigned_to',
            field=models.ForeignKey(
                help_text='Application user assigned to this delivery',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_deliveries',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
