# Generated by Django 5.2.7 on 2026-03-09 08:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0005_add_assigned_to'),
        ('target_management', '0004_marketingtargetparameter_incentive_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryproduct',
            options={'ordering': ['created_at'], 'verbose_name': 'Delivery Product', 'verbose_name_plural': 'Delivery Products'},
        ),
        migrations.AlterUniqueTogether(
            name='deliveryproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deliveryproduct',
            name='bill_number',
            field=models.CharField(blank=True, default='', help_text='Bill number / invoice reference (manual entry)', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='target_management.product'),
        ),
        migrations.AlterField(
            model_name='deliveryproduct',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount for this row (entered by user)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='deliveryproduct',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Avg box value (auto-calculated: total_amount / no_of_boxes)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
