# Generated by Django 5.2.7 on 2026-03-21 06:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0006_add_bill_number_calc_avg_box_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of courier expense')),
                ('bill_value', models.DecimalField(decimal_places=2, help_text='Bill value amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('courier_amount', models.DecimalField(decimal_places=2, help_text='Courier charge amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expense', models.DecimalField(decimal_places=2, default=0, help_text='Total expense (auto-calculated: bill_value + courier_amount)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this entry was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this courier entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courier_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
                'db_table': 'delivery_management_courier',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='delivery_ma_date_0b6987_idx'), models.Index(fields=['-created_at'], name='delivery_ma_created_19fb92_idx')],
            },
        ),
    ]
