# Generated by Django 5.2.7 on 2026-03-21 06:32

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0007_add_courier_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='courier_name',
            field=models.CharField(blank=True, help_text='Courier partner name', max_length=255),
        ),
        migrations.AddField(
            model_name='courier',
            name='customer_address',
            field=models.TextField(blank=True, help_text='Customer address'),
        ),
        migrations.AddField(
            model_name='courier',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name', max_length=255),
        ),
        migrations.AddField(
            model_name='courier',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='courier',
            name='lr_number',
            field=models.CharField(blank=True, help_text='LR / Tracking ID', max_length=100),
        ),
        migrations.AddField(
            model_name='courier',
            name='no_of_cartons',
            field=models.PositiveIntegerField(default=0, help_text='Number of cartons'),
        ),
        migrations.AddField(
            model_name='courier',
            name='order_placed_by',
            field=models.CharField(blank=True, help_text='Name of the person who placed the order', max_length=255),
        ),
        migrations.AddField(
            model_name='courier',
            name='payment_mode',
            field=models.CharField(choices=[('paid', 'Paid'), ('credit', 'Credit')], default='paid', help_text='Payment mode (Paid or Credit)', max_length=20),
        ),
        migrations.AddField(
            model_name='courier',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date received', null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity'),
        ),
        migrations.AddField(
            model_name='courier',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight of the carton in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='courier',
            name='who_prepared',
            field=models.CharField(blank=True, help_text='Entry prepared by', max_length=255),
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['payment_mode'], name='delivery_ma_payment_0cd3bf_idx'),
        ),
    ]
