# Generated by Django 5.2.7 on 2025-11-14 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_management', '0002_alter_usercvdata_interview_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joining_data', models.DateField()),
                ('notice_period', models.IntegerField()),
                ('subject', models.CharField(default='Job Offer Letter')),
                ('body', models.TextField()),
                ('terms_condition', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('candidate_status', models.CharField(choices=[('willing', 'Willing'), ('not_willing', 'Not Willing'), ('sent', 'Sent'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('rejection_status', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadidate', models.OneToOneField(limit_choices_to={'interview_status': 'selected'}, on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='cv_management.usercvdata')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
