# Generated by Django 4.2.7 on 2025-12-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_letter', '0002_offerletter_basic_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='basic_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='conveyance_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='dearness_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='house_rent_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='special_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
