# Generated by Django 5.2.7 on 2026-03-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_letter', '0004_alter_offerletter_basic_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='incentives_parameters',
            field=models.JSONField(blank=True, default=list, help_text='Optional incentive parameter rows shown in generated offer letter', null=True),
        ),
    ]
