# Generated by Django 5.2.7 on 2026-03-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_letter', '0005_add_incentive_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='sales_director_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='sales_director_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
