# Generated by Django 5.2.7 on 2026-03-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_letter', '0006_add_sales_director_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='hr_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
