# Generated by Django 5.2.7 on 2026-04-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollallowance',
            name='allowance_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='deduction_type',
            field=models.CharField(max_length=100),
        ),
    ]
