# Generated by Django 5.2.7 on 2026-05-14 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0010_employee_uan_number'),
        ('payroll', '0002_alter_payrollallowance_allowance_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_date', models.DateField()),
                ('previous_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increment_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('increment_cycle', models.CharField(choices=[('Custom / Manual', 'Custom / Manual'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual')], default='Custom / Manual', max_length=20)),
                ('next_increment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_increments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_increments', to='employee_management.employee')),
            ],
            options={
                'db_table': 'payroll_salarincrement',
                'ordering': ['-increment_date'],
            },
        ),
    ]
