# Generated by Django 5.2.7 on 2026-05-25 11:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_salaryincrement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('late', 'Late Entry Rules'), ('early', 'Early Exit Rules'), ('overtime', 'Overtime Rules'), ('breaks', 'Breaks Rules'), ('earlyOvertime', 'Early Overtime Rules')], max_length=20)),
                ('rule_name', models.CharField(max_length=200)),
                ('threshold_hours', models.IntegerField(default=0)),
                ('threshold_minutes', models.IntegerField(default=0)),
                ('deduct_salary', models.BooleanField(default=False)),
                ('deduction_type', models.CharField(blank=True, choices=[('Fixed Amount', 'Fixed Amount'), ('Percentage', 'Percentage'), ('Half Day', 'Half Day'), ('Full Day', 'Full Day')], max_length=20, null=True)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deduct_half_day', models.BooleanField(default=False)),
                ('deduct_full_day', models.BooleanField(default=False)),
                ('set_occurrences', models.BooleanField(default=False)),
                ('max_occurrences', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_automationrule',
                'ordering': ['rule_type', '-created_at'],
            },
        ),
    ]
