# Generated by Django 5.0.2 on 2026-02-04 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0008_employee_address_employee_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name', max_length=255)),
                ('product_code', models.CharField(blank=True, help_text='Unique product code/SKU', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='Pcs', help_text='Unit of measurement (e.g., Pcs, Kg, Box, Ltr)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'target_management_product',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='CallTargetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the target period')),
                ('end_date', models.DateField(help_text='End date of the target period')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_call_targets', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_targets', to='employee_management.employee')),
            ],
            options={
                'verbose_name': 'Call Target Period',
                'verbose_name_plural': 'Call Target Periods',
                'db_table': 'target_management_call_target_period',
                'ordering': ['-start_date', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='CallDailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(help_text='Specific date for this target')),
                ('target_calls', models.IntegerField(default=0, help_text='Number of calls targeted for this day')),
                ('achieved_calls', models.IntegerField(default=0, help_text='Number of calls achieved')),
                ('productive_calls', models.IntegerField(default=0, help_text='Productive/successful calls')),
                ('order_received', models.IntegerField(default=0, help_text='Orders received')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total order amount', max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_target_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='target_management.calltargetperiod')),
            ],
            options={
                'verbose_name': 'Call Daily Target',
                'verbose_name_plural': 'Call Daily Targets',
                'db_table': 'target_management_call_daily_target',
                'ordering': ['target_date'],
                'unique_together': {('call_target_period', 'target_date')},
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Origin location', max_length=100)),
                ('destination', models.CharField(help_text='Destination location', max_length=100)),
                ('route_code', models.CharField(blank=True, help_text='Unique route code/identifier (optional)', max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Route description or notes')),
                ('is_active', models.BooleanField(default=True, help_text='Is this route currently active?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this route was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this route was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'target_management_route',
                'ordering': ['origin', 'destination'],
            },
        ),
        migrations.CreateModel(
            name='RouteTargetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the target period')),
                ('end_date', models.DateField(help_text='End date of the target period')),
                ('target_boxes', models.DecimalField(decimal_places=2, default=0, help_text='Target in boxes/units', max_digits=10)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, help_text='Target amount in currency', max_digits=12)),
                ('achieved_boxes', models.DecimalField(decimal_places=2, default=0, help_text='Boxes achieved', max_digits=10)),
                ('achieved_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount achieved', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_route_targets', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_targets', to='employee_management.employee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_periods', to='target_management.route')),
            ],
            options={
                'verbose_name': 'Route Target Period',
                'verbose_name_plural': 'Route Target Periods',
                'db_table': 'target_management_route_target_period',
                'ordering': ['-start_date', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='RouteTargetProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('achieved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_target_details', to='target_management.product')),
                ('route_target_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='target_management.routetargetperiod')),
            ],
            options={
                'verbose_name': 'Route Target Product Detail',
                'verbose_name_plural': 'Route Target Product Details',
                'db_table': 'target_management_route_target_product_detail',
            },
        ),
        migrations.CreateModel(
            name='TargetAchievementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('route', 'Route Target'), ('call', 'Call Target')], max_length=20)),
                ('achievement_date', models.DateField(default=django.utils.timezone.now)),
                ('achievement_value', models.DecimalField(decimal_places=2, help_text='Achievement value (quantity/amount/calls)', max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_daily_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievement_logs', to='target_management.calldailytarget')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_logs', to='employee_management.employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_achievements', to=settings.AUTH_USER_MODEL)),
                ('route_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievement_logs', to='target_management.routetargetperiod')),
            ],
            options={
                'verbose_name': 'Target Achievement Log',
                'verbose_name_plural': 'Target Achievement Logs',
                'db_table': 'target_management_achievement_log',
                'ordering': ['-achievement_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin', 'destination'], name='target_mana_origin_60ac74_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_active'], name='target_mana_is_acti_54929c_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['created_at'], name='target_mana_created_baa157_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('origin', 'destination')},
        ),
        migrations.AlterUniqueTogether(
            name='routetargetproductdetail',
            unique_together={('route_target_period', 'product')},
        ),
    ]
