# Generated by Django 5.2.7 on 2026-02-20 04:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.CharField(choices=[('TPA', 'TPA'), ('T_COLLECTION', 'T/Collection'), ('POM', 'POM'), ('SALES_TARGET', 'Sales Target')], help_text='Type of parameter', max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, help_text='Target value for this parameter', max_digits=12)),
                ('incentive_value', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Incentive value for this parameter', max_digits=12, null=True)),
                ('achieved_value', models.DecimalField(decimal_places=2, default=0, help_text='Achieved value (for user manual entry)', max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_target_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_parameters', to='target_management.routetargetperiod')),
            ],
            options={
                'verbose_name': 'Target Parameter',
                'verbose_name_plural': 'Target Parameters',
                'db_table': 'target_management_target_parameters',
                'ordering': ['parameter_type'],
                'unique_together': {('route_target_period', 'parameter_type')},
            },
        ),
    ]
