# Generated by Django 5.2.7 on 2026-02-21 05:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0008_employee_address_employee_date_of_birth_and_more'),
        ('target_management', '0002_targetparameters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingTargetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_marketing_targets', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_targets', to='employee_management.employee')),
            ],
            options={
                'verbose_name': 'Marketing Target Period',
                'verbose_name_plural': 'Marketing Target Periods',
                'db_table': 'target_management_marketing_target_period',
                'ordering': ['-start_date', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketingTargetParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.CharField(choices=[('shops_visited', 'No. of Shops Visited'), ('total_boxes', 'Total Boxes'), ('new_shops', 'New Shops'), ('focus_category', 'Focus Category')], max_length=32)),
                ('parameter_label', models.CharField(blank=True, max_length=64, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('achieved_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketing_target_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_parameters', to='target_management.marketingtargetperiod')),
            ],
            options={
                'verbose_name': 'Marketing Target Parameter',
                'verbose_name_plural': 'Marketing Target Parameters',
                'db_table': 'target_management_marketing_target_parameter',
                'ordering': ['parameter_type'],
                'unique_together': {('marketing_target_period', 'parameter_type')},
            },
        ),
    ]
