# Generated by Django 5.2.7 on 2026-02-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_management', '0003_marketingtargetperiod_marketingtargetparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtargetparameter',
            name='incentive_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
