# Generated by Django 4.2 on 2026-05-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_management', '0004_marketingtargetparameter_incentive_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
