# Generated by Django 6.0.5 on 2026-05-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('target_management', '0005_alter_route_description_alter_route_route_code'),
        ('target_management', '0005_alter_route_route_code'),
    ]

    operations = [
    ]
