# Generated by Django 5.2.7 on 2026-06-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_management', '0006_merge_20260520_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetparameters',
            name='parameter_type',
            field=models.CharField(help_text='Type/name of parameter (free-form, from Parameter Master)', max_length=255),
        ),
    ]
