# Generated by Django 5.0.2 on 2025-10-02 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='users/photos/')),
                ('name', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_level', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('User', 'User')], max_length=20)),
                ('job_role', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Enter a valid phone number.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
