# Generated by Django 5.0.2 on 2025-10-24 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='job_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_level',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
