# Generated by Django 5.0.2 on 2025-11-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_appuser_created_at_appuser_job_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='appuser',
            name='aadhar_attachment',
            field=models.FileField(blank=True, help_text='Aadhar card document', null=True, upload_to='user_documents/aadhar/', verbose_name='Aadhar Card'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='address',
            field=models.TextField(blank=True, help_text='Full residential address', null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='branch',
            field=models.CharField(blank=True, help_text='Bank branch', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='district',
            field=models.CharField(blank=True, help_text='District', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='duty_time_end',
            field=models.TimeField(blank=True, help_text='Daily duty end time', null=True, verbose_name='Duty End Time'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='duty_time_start',
            field=models.TimeField(blank=True, help_text='Daily duty start time', null=True, verbose_name='Duty Start Time'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='education',
            field=models.CharField(blank=True, help_text='Educational qualification', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='experience',
            field=models.CharField(blank=True, help_text='Years of experience', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='Bank IFSC code', max_length=20, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title/position', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date of joining organization', null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization/Department', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='personal_phone',
            field=models.CharField(blank=True, help_text='Personal contact number', max_length=20, null=True, verbose_name='Personal Phone'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='place',
            field=models.CharField(blank=True, help_text='Place/City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='residential_phone',
            field=models.CharField(blank=True, help_text='Residential contact number', max_length=20, null=True, verbose_name='Residential Phone'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='job_role',
            field=models.CharField(blank=True, help_text='Job role (alternative to job_title)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(help_text='Full name', max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone number (legacy field)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_level',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('User', 'User')], default='User', help_text='System access level', max_length=20),
        ),
    ]
