# Generated by Django 5.2.7 on 2025-11-19 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salary Amount')),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_salary_certificate', to=settings.AUTH_USER_MODEL, verbose_name='generated_by')),
            ],
            options={
                'verbose_name': 'SalaryCertificate',
                'verbose_name_plural': 'Salary Certificates',
                'ordering': ['-issued_date'],
            },
        ),
    ]
