# Generated by Django 5.2.7 on 2025-11-21 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_hub', '0001_initial'),
        ('offer_letter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_certificates', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_experience_certificates', to=settings.AUTH_USER_MODEL, verbose_name='generated_by')),
                ('offer_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_certificates', to='offer_letter.offerletter')),
            ],
            options={
                'verbose_name': 'Experience certificate',
                'verbose_name_plural': 'Experience certificate',
            },
        ),
    ]
