# Generated by Django 5.2.7 on 2025-11-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_hub', '0002_experiencecertificate'),
        ('employee_management', '0003_employee_aadhar_number_employee_duty_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencecertificate',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_certificates', to='employee_management.employee', verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='salarycertificate',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_certificates', to='employee_management.employee', verbose_name='Employee'),
        ),
    ]
