# Generated by Django 5.0.2 on 2025-10-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_controll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='key',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
