# Generated by Django 5.0.2 on 2025-10-30 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_controll', '0002_menuitem_icon_menuitem_key_alter_menuitem_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenuaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_controll_menu_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
