# Generated by Django 5.0.2 on 2025-10-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_controll', '0003_alter_usermenuaccess_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermenuaccess',
            table='user_controll_usermenuaccess',
        ),
    ]
