# Generated by Django 5.0.2 on 2025-11-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_controll', '0004_alter_usermenuaccess_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenuaccess',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermenuaccess',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermenuaccess',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
